version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_movie_recommendation
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie-recommendation-system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
